In [1]:
import pandas as pd

In [5]:
path = r"H:\PYTHON\3_ETAPA\atividade_3\Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

dados = pd.read_excel(path, header=None)

In [6]:
print(dados)

                                                    0         1         2  \
0   Tabela 10063 - Pessoas com nível superior comp...       NaN       NaN
1        Brasil, Grande Região e Unidade da Federação     Total       NaN
2                                                 NaN     Total    Homens
3                                              Brasil  25854291  10478534
4                                               Norte   1525166    590558
5                                            Nordeste   4748933   1744994
6                                             Sudeste  12828829   5391638
7                                                 Sul   4338861   1768855
8                                        Centro-Oeste   2412502    982489
9                                            Rondônia    164632     62766
10                                               Acre     84300     33291
11                                           Amazonas    342566    141059
12                                            Roraima     67045     25585
13                                               Pará    601096    229285
14                                              Amapá     89191     35085
15                                          Tocantins    176336     63485
16                                           Maranhão    468681    161352
17                                              Piauí    304955    108371
18                                              Ceará    759303    285013
19                                Rio Grande do Norte    339913    131178
20                                            Paraíba    390742    147221
21                                         Pernambuco    852481    321587
22                                            Alagoas    267996     98462
23                                            Sergipe    218255     80608
24                                              Bahia   1146608    411202
25                                       Minas Gerais   2615434   1031532
26                                     Espírito Santo    491101    193756
27                                     Rio de Janeiro   2243707    942645
28                                          São Paulo   7478587   3223705
29                                             Paraná   1687930    695425
30                                     Santa Catarina   1162515    489557
31                                  Rio Grande do Sul   1488416    583873
32                                 Mato Grosso do Sul    366249    145341
33                                        Mato Grosso    450264    173267
34                                              Goiás    879270    350828
35                                   Distrito Federal    716719    313054
36                    Fonte: IBGE - Censo Demográfico       NaN       NaN

           3                                               4        5  \
0        NaN                                             NaN      NaN
1        NaN  Ciência, Tecnologia, Engenharias e Matemática       NaN
2   Mulheres                                           Total   Homens
3   15375757                                         4149041  2750422
4     934609                                          209657   133055
5    3003939                                          621388   389993
6    7437191                                         2328122  1588874
7    2570005                                          662916   427372
8    1430013                                          326959   211124
9     101866                                           20538    11863
10     51009                                           10364     6237
11    201507                                           52669    34749
12     41460                                            8016     4958
13    371811                                           86691    55481
14     54106                                           11349     7464
15    112851                                           20028    12304
16    307329                                           55068    33820
17    196584                                           37135    21668
18    474290                                           99062    63935
19    208735                                           46857    30398
20    243521                                           52223    33369
21    530893                                          120260    73253
22    169534                                           33596    21398
23    137646                                           29020    17596
24    735406                                          148167    94556
25   1583902                                          452258   291778
26    297344                                           75667    49648
27   1301062                                          406529   265723
28   4254883                                         1393668   981724
29    992505                                          255635   166579
30    672958                                          185742   126554
31    904542                                          221541   134240
32    220908                                           46340    28241
33    276997                                           56776    33307
34    528443                                          116867    74711
35    403665                                          106976    74866
36       NaN                                             NaN      NaN

           6                                               7        8  \
0        NaN                                             NaN      NaN
1        NaN  Educação, Serviços pessoais, Saúde e Bem-estar      NaN
2   Mulheres                                           Total   Homens
3    1398619                                         8079707  1677985
4      76601                                          599785   141169
5     231395                                         1822087   363905
6     739247                                         3652397   768288
7     235543                                         1256291   248574
8     115834                                          749148   156048
9       8675                                           63584    13963
10      4128                                           33379     9121
11     17919                                          121988    30738
12      3057                                           23977     5880
13     31211                                          248397    58128
14      3885                                           36754     9794
15      7724                                           71705    13548
16     21248                                          206222    40667
17     15467                                          128416    25959
18     35126                                          294578    64582
19     16459                                          135434    28273
20     18855                                          150862    30025
21     47007                                          281695    57333
22     12198                                          106971    20060
23     11422                                           83176    16801
24     53612                                          434735    80208
25    160479                                          832482   157960
26     26018                                          161332    29788
27    140805                                          612263   145864
28    411944                                         2046321   434677
29     89056                                          501471    98191
30     59188                                          333537    67571
31     87300                                          421284    82812
32     18100                                          128352    26911
33     23468                                          141121    27052
34     42156                                          288616    56564
35     32109                                          191061    45521
36       NaN                                             NaN      NaN

           9
0        NaN
1        NaN
2   Mulheres
3    6401723
4     458616
5    1458181
6    2884108
7    1007718
8     593101
9      49622
10     24258
11     91249
12     18098
13    190270
14     26960
15     58158
16    165555
17    102457
18    229996
19    107161
20    120837
21    224362
22     86911
23     66376
24    354528
25    674521
26    131544
27    466399
28   1611645
29    403280
30    265964
31    338472
32    101443
33    114069
34    232052
35    145538
36       NaN

In [9]:
df = dados.copy()

In [12]:
df = dados.copy()

# Homens e mulheres por região com curso superior
tabela_curso_superior = df.copy()

tabela_curso_superior.to_excel("curso_superior.xlsx", index=False)


print("=== ESTATÍSTICAS: CURSO SUPERIOR ===")
display(tabela_curso_superior.describe())

=== ESTATÍSTICAS: CURSO SUPERIOR ===

,0,1,2,3,4,5,6,7,8,9
count,36,35,34,34,35,34,34,35,34,34
unique,36,34,34,34,35,34,34,35,34,34
top,Tabela 10063 - Pessoas com nível superior comp...,Total,Homens,Mulheres,"Ciência, Tecnologia, Engenharias e Matemática",Homens,Mulheres,"Educação, Serviços pessoais, Saúde e Bem-estar",Homens,Mulheres
freq,1,2,1,1,1,1,1,1,1,1

In [13]:
# 2. Filtrar os dados da área de Tecnologia/Exatas
tabela_tecnologia = dados.copy() 

tabela_tecnologia.to_excel("tecnologia.xlsx", index=False)
print("=== ESTATÍSTICAS: CIÊNCIA, TECNOLOGIA, ENGENHARIA E MATEMÁTICA ===")
display(tabela_tecnologia.describe())

=== ESTATÍSTICAS: CIÊNCIA, TECNOLOGIA, ENGENHARIA E MATEMÁTICA ===

,0,1,2,3,4,5,6,7,8,9
count,36,35,34,34,35,34,34,35,34,34
unique,36,34,34,34,35,34,34,35,34,34
top,Tabela 10063 - Pessoas com nível superior comp...,Total,Homens,Mulheres,"Ciência, Tecnologia, Engenharias e Matemática",Homens,Mulheres,"Educação, Serviços pessoais, Saúde e Bem-estar",Homens,Mulheres
freq,1,2,1,1,1,1,1,1,1,1

In [14]:
tabela_educacao_saude = dados.copy()

tabela_educacao_saude.to_excel("educacao_saude.xlsx", index=False)

print("=== ESTATÍSTICAS: EDUCAÇÃO, SERVIÇOS, SAÚDE E BEM-ESTAR ===")
display(tabela_educacao_saude.describe())

=== ESTATÍSTICAS: EDUCAÇÃO, SERVIÇOS, SAÚDE E BEM-ESTAR ===

,0,1,2,3,4,5,6,7,8,9
count,36,35,34,34,35,34,34,35,34,34
unique,36,34,34,34,35,34,34,35,34,34
top,Tabela 10063 - Pessoas com nível superior comp...,Total,Homens,Mulheres,"Ciência, Tecnologia, Engenharias e Matemática",Homens,Mulheres,"Educação, Serviços pessoais, Saúde e Bem-estar",Homens,Mulheres
freq,1,2,1,1,1,1,1,1,1,1